// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/greeter/greeter.proto

package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/qeelyn/go-common/protobuf"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_e85324b1145830e1, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Int23                int32    `protobuf:"varint,2,opt,name=int23" json:"int23"`
	Float1               float32  `protobuf:"fixed32,3,opt,name=float1" json:"float1"`
	Double1              float64  `protobuf:"fixed64,4,opt,name=double1" json:"double1"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_e85324b1145830e1, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetInt23() int32 {
	if m != nil {
		return m.Int23
	}
	return 0
}

func (m *Response) GetFloat1() float32 {
	if m != nil {
		return m.Float1
	}
	return 0
}

func (m *Response) GetDouble1() float64 {
	if m != nil {
		return m.Double1
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() {
	proto.RegisterFile("testdata/greeter/greeter.proto", fileDescriptor_greeter_e85324b1145830e1)
}

var fileDescriptor_greeter_e85324b1145830e1 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x41, 0x6b, 0x84, 0x30,
	0x10, 0x85, 0xc9, 0xee, 0xba, 0xae, 0xd3, 0x4b, 0x19, 0x4a, 0x09, 0x52, 0x5a, 0xd9, 0x4b, 0x3d,
	0x45, 0xd6, 0x3d, 0xf5, 0x5e, 0x68, 0xcf, 0xa1, 0x87, 0xde, 0x4a, 0xc4, 0x59, 0x11, 0xa2, 0xb1,
	0x66, 0xfc, 0xff, 0xa5, 0xd1, 0x9c, 0x66, 0x3e, 0x78, 0x7c, 0xbc, 0x07, 0xcf, 0x4c, 0x9e, 0x5b,
	0xc3, 0xa6, 0xea, 0x66, 0x22, 0xa6, 0x39, 0x5e, 0x35, 0xcd, 0x8e, 0x5d, 0xfe, 0xd2, 0x39, 0xd7,
	0x59, 0xaa, 0x02, 0x35, 0xcb, 0xad, 0xe2, 0x7e, 0x20, 0xcf, 0x66, 0x98, 0xd6, 0xc0, 0xf9, 0x1b,
	0x52, 0x4d, 0xbf, 0x0b, 0x79, 0x46, 0x84, 0xc3, 0x68, 0x06, 0x92, 0xa2, 0x10, 0x65, 0xa6, 0xc3,
	0x8f, 0x6f, 0x00, 0x9e, 0xcd, 0xcc, 0x3f, 0xad, 0x61, 0x92, 0xbb, 0x42, 0x94, 0x77, 0x75, 0xae,
	0x56, 0xa9, 0x8a, 0x52, 0xf5, 0x15, 0xa5, 0x3a, 0x0b, 0xe9, 0x77, 0xc3, 0x74, 0x6e, 0xe1, 0xa4,
	0xc9, 0x4f, 0x6e, 0xf4, 0x84, 0xf7, 0xb0, 0x1f, 0x7c, 0xb7, 0x99, 0xff, 0x5f, 0x7c, 0x80, 0xa4,
	0x1f, 0xb9, 0xbe, 0x06, 0x67, 0xa2, 0x57, 0xc0, 0x47, 0x38, 0xde, 0xac, 0x33, 0x7c, 0x91, 0xfb,
	0x42, 0x94, 0x3b, 0xbd, 0x11, 0x4a, 0x48, 0x5b, 0xb7, 0x34, 0x96, 0x2e, 0xf2, 0x50, 0x88, 0x52,
	0xe8, 0x88, 0xf5, 0x2b, 0xa4, 0x1f, 0xeb, 0x62, 0x7c, 0x82, 0xe4, 0x93, 0xac, 0x75, 0x78, 0x52,
	0xdb, 0xa4, 0x3c, 0x53, 0xb1, 0x42, 0x73, 0x0c, 0x6d, 0xaf, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x86, 0xf1, 0xc1, 0x66, 0x32, 0x01, 0x00, 0x00,
}
