// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/greeter/greeter.proto

package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/qeelyn/go-common/protobuf/timestamp"
import wrappers "github.com/qeelyn/go-common/protobuf/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// @inject_tag: gorm:"foreignkey:manager_id"
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" gorm:"foreignkey:manager_id"`
	// @inject_tag: gorm:"foreignkey:manager_id" json:"start_date"
	StartDate            *timestamp.Timestamp  `protobuf:"bytes,2,opt,name=start_date,json=startDate" gorm:"foreignkey:manager_id" json:"start_date"`
	NullString           *wrappers.StringValue `protobuf:"bytes,4,opt,name=null_string,json=nullString" json:"null_string" `
	XXX_NoUnkeyedLiteral struct{}              `json:"-" gorm:"-"`
	XXX_unrecognized     []byte                `json:"-" gorm:"-"`
	XXX_sizecache        int32                 `json:"-" gorm:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_7a7c1d993d3af5eb, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Request) GetNullString() *wrappers.StringValue {
	if m != nil {
		return m.NullString
	}
	return nil
}

type Response struct {
	Msg                  string                `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty" `
	Int23                int32                 `protobuf:"varint,2,opt,name=int23" json:"int23,omitempty" `
	Float1               float32               `protobuf:"fixed32,3,opt,name=float1" json:"float1,omitempty" `
	Double1              *wrappers.DoubleValue `protobuf:"fixed64,4,opt,name=double1" json:"double1" `
	XXX_NoUnkeyedLiteral struct{}              `json:"-" gorm:"-"`
	XXX_unrecognized     []byte                `json:"-" gorm:"-"`
	XXX_sizecache        int32                 `json:"-" gorm:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_7a7c1d993d3af5eb, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetInt23() int32 {
	if m != nil {
		return m.Int23
	}
	return 0
}

func (m *Response) GetFloat1() float32 {
	if m != nil {
		return m.Float1
	}
	return 0
}

func (m *Response) GetDouble1() *wrappers.DoubleValue {
	if m != nil {
		return m.Double1
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() {
	proto.RegisterFile("testdata/greeter/greeter.proto", fileDescriptor_greeter_7a7c1d993d3af5eb)
}

var fileDescriptor_greeter_7a7c1d993d3af5eb = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x3d, 0x6b, 0xf3, 0x30,
	0x10, 0x46, 0xf9, 0xce, 0x65, 0x79, 0x11, 0x2f, 0xc5, 0x98, 0x90, 0x9a, 0x2c, 0xf5, 0x24, 0x13,
	0x07, 0x0a, 0x1d, 0xba, 0x05, 0xda, 0x59, 0x2d, 0x5d, 0x83, 0x8c, 0x2f, 0xc6, 0x20, 0x5b, 0xae,
	0x74, 0xa6, 0x7b, 0xff, 0x44, 0xff, 0x6e, 0x89, 0x64, 0x2f, 0x2d, 0x9d, 0x74, 0x8f, 0x9e, 0x8f,
	0x7b, 0x38, 0xd8, 0x11, 0x3a, 0x2a, 0x15, 0xa9, 0xac, 0xb2, 0x88, 0x84, 0x76, 0x7c, 0x45, 0x67,
	0x0d, 0x99, 0xf8, 0xb6, 0x32, 0xa6, 0xd2, 0x98, 0x79, 0x54, 0xf4, 0x97, 0x8c, 0xea, 0x06, 0x1d,
	0xa9, 0xa6, 0x1b, 0x04, 0xbb, 0x9f, 0x82, 0x0f, 0xab, 0xba, 0x0e, 0xad, 0x0b, 0xfc, 0xfe, 0x8b,
	0xc1, 0x52, 0xe2, 0x7b, 0x8f, 0x8e, 0x38, 0x87, 0x59, 0xab, 0x1a, 0x8c, 0x58, 0xc2, 0xd2, 0xb5,
	0xf4, 0x33, 0x7f, 0x00, 0x70, 0xa4, 0x2c, 0x9d, 0x4b, 0x45, 0x18, 0x4d, 0x12, 0x96, 0x6e, 0xf2,
	0x58, 0x84, 0x50, 0x31, 0x86, 0x8a, 0xd7, 0x71, 0xab, 0x5c, 0x7b, 0xf5, 0x49, 0x11, 0xf2, 0x47,
	0xd8, 0xb4, 0xbd, 0xd6, 0x67, 0x47, 0xb6, 0x6e, 0xab, 0x68, 0xe6, 0xbd, 0xdb, 0x5f, 0xde, 0x17,
	0x4f, 0xbf, 0x29, 0xdd, 0xa3, 0x84, 0xab, 0x21, 0x7c, 0xec, 0x3f, 0x19, 0xac, 0x24, 0xba, 0xce,
	0xb4, 0x0e, 0xf9, 0x3f, 0x98, 0x36, 0xae, 0x1a, 0x9a, 0x5d, 0x47, 0xfe, 0x1f, 0xe6, 0x75, 0x4b,
	0xf9, 0xd1, 0x77, 0x9a, 0xcb, 0x00, 0xf8, 0x0d, 0x2c, 0x2e, 0xda, 0x28, 0x3a, 0x44, 0xd3, 0x84,
	0xa5, 0x13, 0x39, 0x20, 0x7e, 0x0f, 0xcb, 0xd2, 0xf4, 0x85, 0xc6, 0xc3, 0x9f, 0x3d, 0x4e, 0x9e,
	0x0f, 0x3d, 0x46, 0x71, 0x7e, 0x07, 0xcb, 0xa7, 0x70, 0x70, 0xbe, 0x85, 0xf9, 0x33, 0x6a, 0x6d,
	0xf8, 0x4a, 0x0c, 0x07, 0x8b, 0xd7, 0x62, 0x2c, 0x58, 0x2c, 0x7c, 0xce, 0xf1, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x6c, 0xf0, 0xf2, 0x80, 0xb1, 0x01, 0x00, 0x00,
}
